services:
  phoenix:
    image: arizephoenix/phoenix:latest
    pull_policy: always
    env_file:
      - .env
    ports:
      - "${PHOENIX_PORT}:${PHOENIX_PORT}"
    volumes:
      - ./data/phoenix:/root/.phoenix  # Mount a local directory to persist data
  backend:
    build: backend
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:${PORT}"]
      interval: 5s
      timeout: 1s
      retries: 5
